{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0\n"
     ]
    }
   ],
   "source": [
    "from datasets import load_dataset, load_from_disk\n",
    "\n",
    "from setfit import SetFitModel, SetFitTrainer\n",
    "\n",
    "import torch\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "# set to True to use the gpu (if there is one available)\n",
    "use_gpu = True\n",
    "\n",
    "# select device\n",
    "if torch.cuda.is_available():\n",
    "    device = torch.cuda.current_device()\n",
    "else:\n",
    "    device =  -1\n",
    "print(device)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2\n",
      "2\n",
      "0\n",
      "0\n",
      "0\n",
      "2\n",
      "0\n",
      "1\n",
      "2\n",
      "0\n",
      "2\n",
      "0\n",
      "2\n",
      "2\n",
      "0\n",
      "3\n",
      "0\n",
      "2\n"
     ]
    }
   ],
   "source": [
    "dataset = load_from_disk(\"data/belief_dataset/\")\n",
    "\n",
    "data_dict = dataset.train_test_split(test_size=0.95)\n",
    "train_ds = data_dict['train']\n",
    "\n",
    "for entry in train_ds:\n",
    "    print(entry['label'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "model_head.pkl not found on HuggingFace Hub, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.\n"
     ]
    }
   ],
   "source": [
    "test_ds = data_dict['test']\n",
    "\n",
    "from sentence_transformers.losses import CosineSimilarityLoss\n",
    "\n",
    "model = SetFitModel.from_pretrained(\"sentence-transformers/all-mpnet-base-v2\")\n",
    "trainer = SetFitTrainer(\n",
    "    model=model,\n",
    "    train_dataset=train_ds,\n",
    "    eval_dataset=test_ds,\n",
    "    loss_class=CosineSimilarityLoss,\n",
    "    batch_size=4,\n",
    "    num_iterations=20, # Number of text pairs to generate for contrastive learning\n",
    "    num_epochs=1 # Number of epochs to use for contrastive learning\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "***** Running training *****\n",
      "  Num examples = 720\n",
      "  Num epochs = 1\n",
      "  Total optimization steps = 180\n",
      "  Total train batch size = 4\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "9af5b06697904f1898e32a3a727b140d",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Epoch:   0%|          | 0/1 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "2b453bdabca04d03bb435c0b1b35f0fe",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Iteration:   0%|          | 0/180 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "***** Running evaluation *****\n"
     ]
    }
   ],
   "source": [
    "# Train and evaluate!\n",
    "trainer.train()\n",
    "metrics = trainer.evaluate()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "trainer.model._save_pretrained(save_directory=\"models/few-shot-mpnet-base-v2\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Some weights of the model checkpoint at models/few-shot-mpnet-base-v2/ were not used when initializing MPNetForSequenceClassification: ['pooler.dense.bias', 'pooler.dense.weight']\n",
      "- This IS expected if you are initializing MPNetForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).\n",
      "- This IS NOT expected if you are initializing MPNetForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).\n",
      "Some weights of MPNetForSequenceClassification were not initialized from the model checkpoint at models/few-shot-mpnet-base-v2/ and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.weight', 'classifier.out_proj.bias']\n",
      "You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.\n",
      "Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.\n"
     ]
    }
   ],
   "source": [
    "from transformers import pipeline\n",
    "classifier = pipeline(\"zero-shot-classification\",\n",
    "                      model=\"models/few-shot-mpnet-base-v2/\", device=device)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "8d3121329f444e1fab5b35fa05547824",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/173 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 346 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 347 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 348 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 349 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 350 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 351 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 352 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 353 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 354 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 355 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 356 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 357 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 358 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 359 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 360 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 361 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 362 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 363 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 364 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 365 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 366 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 367 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 368 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 369 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 370 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 371 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 372 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 373 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 374 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 375 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 376 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 377 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 378 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 379 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 380 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 381 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 382 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 383 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 384 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 385 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 386 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 387 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 388 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 389 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 390 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 391 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 392 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 393 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 394 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 395 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 396 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 397 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 398 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 399 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 400 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 401 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 402 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 403 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 404 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 405 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 406 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 407 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 408 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 409 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 410 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 411 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 412 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 413 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 414 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 415 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 416 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 417 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 418 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 419 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 420 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 421 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 422 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 423 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 424 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 425 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 426 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 427 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 428 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 429 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 430 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 431 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 432 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 433 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 434 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 435 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 436 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 437 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 438 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 439 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 440 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 441 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 442 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 443 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 444 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 445 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 446 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 447 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 448 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 449 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 450 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 451 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 452 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 453 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 454 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 455 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 456 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 457 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 458 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 459 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 460 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 461 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 462 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 463 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 464 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 465 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 466 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 467 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 468 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 469 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 470 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 471 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 472 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 473 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 474 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 475 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 476 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 477 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 478 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 479 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 480 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 481 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 482 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 483 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 484 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 485 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 486 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 487 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 488 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 489 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 490 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 491 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 492 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 493 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 494 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 495 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 496 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 497 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 498 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 499 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 500 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 501 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 502 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 503 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 504 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 505 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 506 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 507 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 508 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 509 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 510 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 511 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 512 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 513 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 514 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 515 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 516 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 517 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 518 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 519 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 520 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 521 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 522 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 523 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 524 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 525 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 526 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 527 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 528 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 529 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 530 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 531 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 532 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 533 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 534 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 535 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 536 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 537 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 538 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 539 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 540 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 541 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 542 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 543 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 544 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 545 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 546 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 547 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 548 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 549 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 550 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 551 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 552 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 553 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 554 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 555 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 556 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 557 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 558 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 559 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 560 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 561 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 562 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 563 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 564 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 565 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 566 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 567 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 568 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 569 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 570 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 571 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 572 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 573 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 574 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 575 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 576 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 577 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 578 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 579 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 580 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 581 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 582 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 583 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 584 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 585 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 586 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 587 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 588 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 589 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 590 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 591 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 592 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 593 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 594 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 595 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 596 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 597 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 598 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 599 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 600 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 601 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 602 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 603 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 604 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 605 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 606 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 607 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 608 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 609 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 610 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 611 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 612 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 613 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 614 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 615 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 616 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 617 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 618 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 619 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 620 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 621 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 622 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 623 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 624 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 625 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 626 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 627 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 628 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 629 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 630 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 631 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 632 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 633 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 634 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 635 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 636 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 637 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 638 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 639 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 640 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 641 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 642 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 643 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 644 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 645 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 646 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 647 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 648 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 649 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 650 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 651 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 652 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 653 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 654 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 655 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 656 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 657 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 658 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 659 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 660 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 661 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 662 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 663 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 664 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 665 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 666 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 667 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 668 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 669 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 670 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 671 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 672 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 673 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 674 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 675 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 676 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 677 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 678 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 679 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 680 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 681 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 682 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 683 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 684 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 685 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 686 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 687 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 688 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 689 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x000002992FF57FD0> was reported to be 345 (when accessing len(dataloader)), but 690 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n"
     ]
    }
   ],
   "source": [
    "from transformers.pipelines.pt_utils import KeyDataset\n",
    "from tqdm.auto import tqdm\n",
    "\n",
    "labels = [\"neither\", \"negative\", \"positive\", \"both\"]\n",
    "pred_i_list = []\n",
    "for pred in tqdm(classifier(KeyDataset(test_ds, \"text\"), batch_size=2, candidate_labels=labels)):\n",
    "    pred_i = labels.index(pred[\"labels\"][0])\n",
    "    pred_i_list.append(pred_i)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "              precision    recall  f1-score   support\n",
      "\n",
      "     neither       0.00      0.00      0.00       114\n",
      "    negative       0.24      0.31      0.27        64\n",
      "    positive       0.40      0.76      0.53       139\n",
      "        both       0.00      0.00      0.00        28\n",
      "\n",
      "    accuracy                           0.37       345\n",
      "   macro avg       0.16      0.27      0.20       345\n",
      "weighted avg       0.21      0.37      0.26       345\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\sklearn\\metrics\\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, msg_start, len(result))\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\sklearn\\metrics\\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, msg_start, len(result))\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\sklearn\\metrics\\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, msg_start, len(result))\n"
     ]
    }
   ],
   "source": [
    "from sklearn.metrics import classification_report\n",
    "\n",
    "y_true = test_ds[\"label\"]\n",
    "y_pred = pred_i_list\n",
    "print(classification_report(y_true, y_pred, target_names=labels))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "tf-gpu",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.12"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
