{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0\n"
     ]
    }
   ],
   "source": [
    "import torch\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "# set to True to use the gpu (if there is one available)\n",
    "use_gpu = True\n",
    "\n",
    "# select device\n",
    "if torch.cuda.is_available():\n",
    "    device = torch.cuda.current_device()\n",
    "else:\n",
    "    device =  -1\n",
    "print(device)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "762f98f91362453c90055d43a0a3a42b",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Downloading pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Some weights of the model checkpoint at sentence-transformers/all-mpnet-base-v2 were not used when initializing MPNetForSequenceClassification: ['pooler.dense.weight', 'pooler.dense.bias']\n",
      "- This IS expected if you are initializing MPNetForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).\n",
      "- This IS NOT expected if you are initializing MPNetForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).\n",
      "Some weights of MPNetForSequenceClassification were not initialized from the model checkpoint at sentence-transformers/all-mpnet-base-v2 and are newly initialized: ['classifier.out_proj.bias', 'classifier.out_proj.weight', 'classifier.dense.weight', 'classifier.dense.bias']\n",
      "You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "a3e40fa4767b43318477fbcb4bf067f6",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Downloading (…)okenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "92038ca9fce74c52abffb3b69630d09f",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Downloading (…)solve/main/vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "633944c4160d4675845d4bb6b7d1f7cf",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Downloading (…)/main/tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "f7115a79546f45189d4e9a4ed99f180e",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Downloading (…)cial_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.\n"
     ]
    }
   ],
   "source": [
    "from transformers import pipeline\n",
    "classifier = pipeline(\"zero-shot-classification\",\n",
    "                      model=\"sentence-transformers/all-mpnet-base-v2\", device=device)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>text</th>\n",
       "      <th>sentiment</th>\n",
       "      <th>label</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Also use of chemicals and machinery on their p...</td>\n",
       "      <td>NEGATIVE, NEGATIVE</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Sources believe that twenty-five to 30 percent...</td>\n",
       "      <td>UNDETERMINED</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Although these government-led initiatives are ...</td>\n",
       "      <td>UNDETERMINED</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>In other projects of this kind, it is not alwa...</td>\n",
       "      <td>POSITIVE</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Many African policy makers evidently believe t...</td>\n",
       "      <td>POSITIVE</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>358</th>\n",
       "      <td>Similar initiatives have and can be initiated ...</td>\n",
       "      <td>POSITIVE</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>359</th>\n",
       "      <td>Collective sales account for an average of 64 ...</td>\n",
       "      <td>UNDETERMINED</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>360</th>\n",
       "      <td>Individual sales account for slightly lower vo...</td>\n",
       "      <td>UNDETERMINED, UNDETERMINED, UNDETERMINED</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>361</th>\n",
       "      <td>Modernization of the rice value chain The VC t...</td>\n",
       "      <td>UNDETERMINED</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>362</th>\n",
       "      <td>Small-scale processors use mills to husk the r...</td>\n",
       "      <td>UNDETERMINED</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>363 rows × 3 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                  text  \\\n",
       "0    Also use of chemicals and machinery on their p...   \n",
       "1    Sources believe that twenty-five to 30 percent...   \n",
       "2    Although these government-led initiatives are ...   \n",
       "3    In other projects of this kind, it is not alwa...   \n",
       "4    Many African policy makers evidently believe t...   \n",
       "..                                                 ...   \n",
       "358  Similar initiatives have and can be initiated ...   \n",
       "359  Collective sales account for an average of 64 ...   \n",
       "360  Individual sales account for slightly lower vo...   \n",
       "361  Modernization of the rice value chain The VC t...   \n",
       "362  Small-scale processors use mills to husk the r...   \n",
       "\n",
       "                                    sentiment  label  \n",
       "0                          NEGATIVE, NEGATIVE      1  \n",
       "1                                UNDETERMINED      0  \n",
       "2                                UNDETERMINED      0  \n",
       "3                                    POSITIVE      2  \n",
       "4                                    POSITIVE      2  \n",
       "..                                        ...    ...  \n",
       "358                                  POSITIVE      2  \n",
       "359                              UNDETERMINED      0  \n",
       "360  UNDETERMINED, UNDETERMINED, UNDETERMINED      0  \n",
       "361                              UNDETERMINED      0  \n",
       "362                              UNDETERMINED      0  \n",
       "\n",
       "[363 rows x 3 columns]"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "labels = open('data/classes.txt').read().splitlines()\n",
    "all_df = pd.read_csv(\"data/belief_benchmark.csv\")\n",
    "all_df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Dataset({\n",
       "    features: ['text', 'sentiment', 'label'],\n",
       "    num_rows: 363\n",
       "})"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from datasets import Dataset\n",
    "\n",
    "dataset = Dataset.from_pandas(all_df)\n",
    "#dataset.save_to_disk(\"data/belief_dataset\")\n",
    "dataset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "a78efab79317482290288210f8cdde7e",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/182 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 364 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 365 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 366 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 367 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 368 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 369 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 370 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 371 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 372 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 373 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 374 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 375 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 376 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 377 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 378 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 379 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 380 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 381 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 382 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 383 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 384 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 385 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 386 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 387 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 388 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 389 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 390 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 391 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 392 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 393 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 394 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 395 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 396 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 397 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 398 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 399 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 400 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 401 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 402 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 403 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 404 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 405 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 406 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 407 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 408 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 409 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 410 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 411 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 412 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 413 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 414 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 415 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 416 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 417 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 418 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 419 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 420 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 421 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 422 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 423 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 424 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 425 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 426 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 427 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 428 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 429 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 430 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 431 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 432 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 433 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 434 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 435 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 436 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 437 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 438 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 439 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 440 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 441 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 442 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 443 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 444 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 445 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 446 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 447 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 448 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 449 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 450 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 451 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 452 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 453 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 454 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 455 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 456 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 457 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 458 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 459 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 460 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 461 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 462 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 463 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 464 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 465 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 466 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 467 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 468 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 469 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 470 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 471 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 472 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 473 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 474 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 475 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 476 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 477 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 478 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 479 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 480 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 481 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 482 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 483 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 484 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 485 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 486 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 487 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 488 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 489 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 490 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 491 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 492 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 493 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 494 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 495 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 496 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 497 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 498 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 499 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 500 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 501 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 502 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 503 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 504 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 505 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 506 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 507 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 508 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 509 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 510 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 511 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 512 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 513 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 514 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 515 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 516 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 517 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 518 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 519 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 520 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 521 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 522 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 523 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 524 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 525 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 526 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 527 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 528 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 529 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 530 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 531 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 532 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 533 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 534 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 535 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 536 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 537 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 538 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 539 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 540 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 541 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 542 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 543 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 544 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 545 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 546 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 547 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 548 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 549 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 550 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 551 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 552 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 553 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 554 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 555 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 556 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 557 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 558 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 559 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 560 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 561 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 562 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 563 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 564 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 565 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 566 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 567 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 568 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 569 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 570 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 571 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 572 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 573 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 574 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 575 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 576 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 577 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 578 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 579 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 580 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 581 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 582 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 583 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 584 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 585 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 586 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 587 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 588 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 589 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 590 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 591 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 592 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 593 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 594 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 595 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 596 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 597 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 598 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 599 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 600 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 601 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 602 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 603 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 604 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 605 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 606 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 607 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 608 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 609 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 610 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 611 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 612 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 613 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 614 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 615 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 616 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 617 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 618 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 619 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 620 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 621 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 622 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 623 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 624 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 625 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 626 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 627 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 628 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 629 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 630 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 631 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 632 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 633 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 634 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 635 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 636 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 637 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 638 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 639 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 640 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 641 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 642 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 643 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 644 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 645 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 646 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 647 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 648 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 649 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 650 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 651 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 652 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 653 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 654 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 655 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 656 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 657 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 658 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 659 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 660 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 661 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 662 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 663 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 664 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 665 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 666 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 667 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 668 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 669 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 670 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 671 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 672 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 673 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 674 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 675 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 676 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 677 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 678 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 679 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 680 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 681 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 682 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 683 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 684 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 685 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 686 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 687 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 688 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 689 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 690 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 691 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 692 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 693 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 694 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 695 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 696 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 697 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 698 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 699 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 700 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 701 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 702 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 703 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 704 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 705 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 706 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 707 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 708 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 709 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 710 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 711 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 712 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 713 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 714 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 715 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 716 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 717 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 718 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 719 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 720 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 721 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 722 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 723 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 724 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 725 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n",
      "c:\\Users\\conni\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\torch\\utils\\data\\dataloader.py:529: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x00000159D025C6A0> was reported to be 363 (when accessing len(dataloader)), but 726 samples have been fetched. \n",
      "  warnings.warn(warn_msg)\n"
     ]
    }
   ],
   "source": [
    "from transformers.pipelines.pt_utils import KeyDataset\n",
    "from tqdm.auto import tqdm\n",
    "\n",
    "labels = [\"neither\", \"negative\", \"positive\", \"both\"]\n",
    "pred_i_list = []\n",
    "for pred in tqdm(classifier(KeyDataset(dataset, \"text\"), batch_size=2, candidate_labels=labels)):\n",
    "    pred_i = labels.index(pred[\"labels\"][0])\n",
    "    pred_i_list.append(pred_i)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "              precision    recall  f1-score   support\n",
      "\n",
      "     neither       0.42      0.04      0.07       122\n",
      "    negative       0.18      0.31      0.23        65\n",
      "    positive       0.46      0.47      0.46       147\n",
      "        both       0.09      0.28      0.13        29\n",
      "\n",
      "    accuracy                           0.28       363\n",
      "   macro avg       0.29      0.27      0.23       363\n",
      "weighted avg       0.37      0.28      0.26       363\n",
      "\n"
     ]
    }
   ],
   "source": [
    "from sklearn.metrics import classification_report\n",
    "\n",
    "y_true = all_df[\"label\"]\n",
    "y_pred = pred_i_list\n",
    "print(classification_report(y_true, y_pred, target_names=labels))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "55"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mThe Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click <a href='https://aka.ms/vscodeJupyterKernelCrash'>here</a> for more info. View Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "import gc\n",
    "with torch.no_grad():\n",
    "    torch.cuda.empty_cache()\n",
    "gc.collect()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.12"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
